server:
  port: 8081
  servlet:
    session:
      tracking-modes: cookie

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: koji
    password: passw0rd1!
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

uploadFile:
  path: /home/koji/koji-mall/S3Images/

cloud:
  aws:
    credentials:
      accessKey: AKIA26MX4NM4A6YPS4HI
      secretKey: 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

    stack:
      auto: false
    s3:
      bucket: bucketforkoji
      bucketUrl: https://s3.ap-northeast-2.amazonaws.com/bucketforkoji/
    region:
      static: ap-northeast-2
