server:
  port: 8081
  servlet:
    session:
      tracking-modes: cookie

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: koji
    password: passw0rd1!
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace